# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c6949cff4c26f832179e58376f6a007a25fce16cde1b861924f97434af8602d4babdbae56f02146d2caa75de6f10672ce9b68e955adca4553632d998a13dea33

test:
  secret_key_base: 6db008d3f5ff704bb2448388f3f6cb1030ea726f618f7cdebcd01a826aea59338953858cf30f6c5903c562e7c7ccceb30d0fb12f0a23d016bf2bc9016a797e12

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
